swagger: '2.0'
info:
  title: Info API
  description: Stealth Worker API for accessing public data
  version: "1.0.0"

host: info.stealthworker.com

schemes:
  - https
basePath: /v1

# CORS

produces:
  - application/json+vnd.api
paths:
  /skills:
    get:
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Skill'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Skill:
    type: object
    description: Published Skills
    properties:
      name:
        type: string
        description: Name of the skill
      description:
        type: string
        description: Description of the skill
      pictureUrl:
        type: string
        description: Picture URL for the skill
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
